name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          repository: mahmoud-24/shiftEV-task
          ref: main

      - name: Login to Digital Ocean Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Build latest
        run: docker build -t registry.digitalocean.com/mmelegy/shiftev-app .

      - name: Push to Digital Ocean Registry
        run: docker push registry.digitalocean.com/mmelegy/shiftev-app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      run: |
          curl -sL https://github.com/digitalocean/doctl/releases/latest/download/doctl-$(uname -s)-$(uname -m) -o /usr/local/bin/doctl
          chmod +x /usr/local/bin/doctl
          doctl auth init -t ${{ secrets.DIGITAL_OCEAN_TOKEN }
    - name: DigitalOcean App Platform deployment
      run: |
          doctl apps update shiftev-app --spec app-spec.yaml
      env:
          DOCTL_API_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        #uses: digitalocean/app_action@v1.1.5
        # with:
        #   app_name: shiftev-app
        #   token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        #   images: '[{
        #               "name": "shiftev-app",
        #               "repository": "registry.digitalocean.com/mmelegy/shiftev-app",
        #               "tag": "latest"
        #              }]'
